name: Deploy backend image to GHCR
  
on:
  push:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './backend'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3
        
        # Set the unique tag based on the commit SHA
      - name: Set Docker tag
        run: echo "IMAGE_TAG=$GITHUB_SHA" >> $GITHUB_ENV
            
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
              
      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/gravitee-io-labs/trial-app-backend:latest
          docker push ghcr.io/gravitee-io-labs/trial-app-backend:$IMAGE_TAG
